# Generated by Django 5.1.2 on 2024-11-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusiciansModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('instrument_type', models.CharField(choices=[('Violin', 'Violin'), ('Guitar', 'Guitar'), ('Drums', 'Drums'), ('Keyboard', 'Keyboard')], max_length=8)),
            ],
        ),
    ]
